version: '3'

services:
  cabin_db:
    image: mysql:latest
    container_name: onehs-mysql-container

    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: blog-mysql
      MYSQL_USER: secret
      MYSQL_PASSWORD: 123